const apiKeys = {
  appConfig: 'server/configuration',
  signUp: 'users/registration/complete',
  login: 'users/token',
  profile: 'users/profile',
  SSOLogin: 'sso/login',
  bulkUpload: 'users/bulk/upload',
  participantList: 'users/list',
  formData: 'forms/list',
  initiateParticipant: 'users/initiate',
  updateParticipant: 'users/update',
  resendSurvey: 'users/resend/survey',
  deleteParticipant: 'users/delete',
  participantDetails: 'users/details',
  // signatureUpload: 'eicf/signature/upload',
  signatureUpload: 'eicfform/signature/upload',

  registerAnynomousParticipant: 'users/participant',
  managersList: 'users/managers/list',
  auditList: 'study/admin/audit/logs',

  //eicf
  eicfListPublished: 'eicf/published',
  // eICFUpdateStatus: 'eicf/update/status',
  // deleteEICF: 'eicf/delete',
  // eicfList: 'eicf',
  // eicfInfo: 'eicf/info',
  // eicfAdd: 'eicf',
  // eicfUpdate: 'eicf/update',
  eICFUpdateStatus: 'eicfform/update/status',
  deleteEICF: 'eicfform/delete',
  eicfList: 'eicfform',
  eicfInfo: 'eicfform/info',
  eicfAdd: 'eicfform',
  eicfUpdate: 'eicfform/update',
  getEicfList: 'eicfform/list',
  survey: 'survey',
  syncRecords: 'survey/sync/records',
  eicfSelectedData: 'cde/icef',
  participantForms: 'users/participant/forms',

  //forms
  forms: 'forms',
  addForm: 'forms',
  formInfo: 'forms/info',
  deleteForm: 'forms/delete',
  formUpdate: 'forms/update',
  formListPublished: 'forms/published',
  formUpdateStatus: 'forms/update/status',
  cdePublished: 'cde',
  formDetails: 'forms/details',
  cdeSummary: 'cde/summary',
  cdeCategory: 'cde/category',
  dependencyforms: 'forms/dependencyforms',
  //  Multirole selection
  multiRoleSelection: 'users/reset/token',

  // Analytics
  feedback: 'analytics/feedback',
  participantsEnrolled: 'analytics/participants/enrolled',
  syncedRecords: 'analytics/synced/records',
  surveyStats: 'analytics/survey/stats',
  avgTime: 'analytics/survey/avgTime',

  //survey
  surveyFeedback: 'feedback/submit',
  surveyInfo: 'survey/info',
  surveySubmit: 'survey/submit',
  surveyResubmit: 'survey/resubmit',
  surveyDetails: 'survey/details',
  getSyncedRecords: 'survey/sync/records',
  getFeedback: 'survey/feedback',
  surveyBundle: 'survey/bundle',
  eicfDetails: 'survey/eicf/details',

  //Study
  addStudy: 'study/create',
  updateStudy: 'study/update',
  armList: 'study/arms',
  fetchDocumentsByStudy: 'study/document/',
  uploadStudyDocument: 'study/document/upload',
  studyManagementList: 'study',
  studyDetails: 'study/details/',
  getStudiesData: 'study/stats',
  studyCDEs: 'studycde',
  addStudyAmins: 'study/admins',
  getStudyAmins: 'study/admins',
  studyStatusUpdate: 'study/status/update',
  statusUpdate: 'study/document/update',
  createTemplate: 'study/email/template/create',
  deleteTemplate: 'study/email/template/delete',
  getTemplate: 'study/email/template/list',
  statusContantUpdate: 'study/content/update',
  studyContent: 'study/details/',

  //userManagement
  DeleteUser: 'study/managers/status',
  UserList: 'users/managers/list',
  AddUser: 'study/managers',
};

export default apiKeys;
